# Javascript Node CircleCI 2.0 configuration file
version: 2
jobs:
  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "./yarn.lock" }}
      - run: yarn
      - run: yarn build
      - run: yarn lint
      - run: yarn stylelint
      - save_cache:
          key: dependency-cache-{{ checksum "./yarn.lock" }}
          paths:
            - ./node_modules
            - ./.next/cache

  build:
    docker:
      - image: circleci/node:12
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build . -t $DOCKER_USER/production-ready-webapp-boilerplate:${CIRCLE_BRANCH}
      - run: docker push $DOCKER_USER/production-ready-webapp-boilerplate:${CIRCLE_BRANCH}

  deploy:
    machine: true
    steps:
      - run: ssh admin@haoictdev.com "docker pull $DOCKER_USER/production-ready-webapp-boilerplate:${CIRCLE_BRANCH}; docker kill pokemon || true; docker rm pokemon || true"
      - run: ssh admin@haoictdev.com "docker run --name pokemon --restart always -d -p 3005:3005 -v /home/admin/docker/bindmount/pokemon/.env:/usr/src/app/.env $DOCKER_USER/production-ready-webapp-boilerplate:${CIRCLE_BRANCH}"

  build-storybook:
    docker:
      - image: circleci/node:12
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build . -f Dockerfile-storybook -t $DOCKER_USER/production-ready-webapp-boilerplate-storybook:${CIRCLE_BRANCH}
      - run: docker push $DOCKER_USER/production-ready-webapp-boilerplate-storybook:${CIRCLE_BRANCH}

  deploy-storybook:
    machine: true
    steps:
      - run: ssh admin@haoictdev.com "docker pull $DOCKER_USER/production-ready-webapp-boilerplate-storybook:${CIRCLE_BRANCH}; docker kill pokemon-storybook || true; docker rm pokemon-storybook || true"
      - run: ssh admin@haoictdev.com "docker run --name pokemon-storybook --restart always -d -p 3006:9090 $DOCKER_USER/production-ready-webapp-boilerplate-storybook:${CIRCLE_BRANCH}"

  cleanup:
    machine: true
    steps:
      - run: ssh admin@haoictdev.com "docker image prune -f"

workflows:
  version: 2

  test-build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - build-storybook:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy-storybook:
          requires:
            - build-storybook
          filters:
            branches:
              only:
                - master
      - cleanup:
          requires:
            - deploy
            - deploy-storybook
