# Javascript Node CircleCI 2.0 configuration file
version: 2
jobs:
  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "./yarn.lock" }}
      - run: yarn
      - run: yarn build
      - save_cache:
          key: dependency-cache-{{ checksum "./yarn.lock" }}
          paths:
            - ./node_modules
            - ./.next/cache

  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build . -t $DOCKER_USER/production-ready-webapp-boilerplate:${CIRCLE_BRANCH}
      - run: docker push $DOCKER_USER/production-ready-webapp-boilerplate:${CIRCLE_BRANCH}

  deploy:
    machine: true
    steps:
      - run: ssh admin@nless.pro "docker pull $DOCKER_USER/production-ready-webapp-boilerplate:${CIRCLE_BRANCH}; docker kill pokemon || true; docker rm pokemon || true"
      - run: ssh admin@nless.pro "docker run --name pokemon --restart always -d -p 3005:3005 -v /home/admin/docker/bindmount/pokemon/.env:/usr/src/app/.env $DOCKER_USER/production-ready-webapp-boilerplate:${CIRCLE_BRANCH}"
      - run: ssh admin@nless.pro "docker image prune -f"

workflows:
  version: 2

  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
